### ISSUE TITLE
Questions about Watchy

### ISSUE THREAD

**Issue by Izaic** [sqfmi/Watchy#6]
I was made aware of this watch by a article on CNX-software. In the post they mentioned this watch supports Micropython.

How does the micropython support work? 
How is this device charged? 
Does it already have the ability to sync over bluetooth to a phone for firmware updates and time sync?

**Comment by robertio** [comment]
Hi,
What dimension in mm?
Is there case for it?
Can you please provide actual device pictures from different views? 
What specification it has ?  like weight, battery size? 

Best regards,
Robert

**Comment by biasedlogic** [comment]
Don't bother. I just got it delivered. The paper-thin e-Ink glass is stuck with a piece of double-sided tape on top of an ESP32 unit, display edges and corners completely unsupported and free to catch on everything. There's no solution to mount the battery - not even a patch of double sided foam tape. The wrist strap shares a slot with the flex foil of the display - see how long will it live... and the hardest thing: there's no firmware to speak of beyond a 'hello world' - a 'clock' that hasn't got even as much of an UI as to allow to set time. Smartwatch as in smartphone-connected? forget it. It's dumber out of the box than a most basic LCD watch. Forget what's shown on sqfmi webpage.
I regret dropping any money on it, leave alone $55.

**Comment by biasedlogic** [comment]
> Hi,
> What dimension in mm?

45.7 tall, 34mm wide, about 10mm thick without battery - there's no battery mount, included pouch battery is 4mm thick

> Is there case for it?

No. I may design one, unless i throw this 'watch' (which is equivalent to a 'esp32 development kit with display' if you name it properly) in the bin.

> Can you please provide actual device pictures from different views?
![IMG_20200409_110118](https://user-images.githubusercontent.com/15014372/78878122-2bdc8280-7a52-11ea-89e3-a7c81e85fe1d.jpg)
![IMG_20200409_110125](https://user-images.githubusercontent.com/15014372/78878213-4f9fc880-7a52-11ea-9e39-9637066f05d5.jpg)
![IMG_20200409_110122](https://user-images.githubusercontent.com/15014372/78878237-58909a00-7a52-11ea-8bfa-e666350116ef.jpg)
![IMG_20200409_110114](https://user-images.githubusercontent.com/15014372/78878249-5cbcb780-7a52-11ea-90d6-f3e0d11fcb33.jpg)

> What specification it has ? like weight, battery size?

Battery is 200mAh lipo pouch. Onboard charger charges it at 110mA. No battery management chips, like coulomb meter or such.

> Best regards,
> Robert

Greets
Marek

**Comment by biasedlogic** [comment]
And here comes the bare PCB

![IMG_20200409_111034](https://user-images.githubusercontent.com/15014372/78878596-eec4c000-7a52-11ea-98e4-e0053441af79.jpg)

Note: I have replaced the buzzer motor, the original had too short wires and was sitting over the components in the middle of the board, uptilting the display glass (to which it was glued btw, instead of the PCB):
![IMG_20200409_111026](https://user-images.githubusercontent.com/15014372/78878608-f2584700-7a52-11ea-858b-73a98778c4cd.jpg)

**Comment by biasedlogic** [comment]
https://www.thingiverse.com/thing:4272622

I designed a basic case for this hardware. It's no prettier than the 'watch' itself, but it shall protect the hardware while I try to figure out some use for it. I don't think I'm gonna wear it ;-) so the case will likely evolve towards some weather station or something of that sort.

**Comment by robertio** [comment]
Dear Biasedlogic.
Many thanks for the very detailed and highly informative pictures!!
 I appreciate your work. So thank you!

 I am smiling to see you how you changed your mind from "garbage" to "a good toy" :)
 you spent a lot of time to enhance it. the case is a god start, for custom ones.

 I ordered [https://www.waveshare.com/product/1.54inch-e-paper-b.htm](url)
And https://www.waveshare.com/e-Paper-ESP32-Driver-Board.htm to have dev board for the future developments. 
I will see how is work.
I plan micropython to run on it.
I've some Esp8266 experience with micropython.

**Comment by biasedlogic** [comment]
> Dear Biasedlogic.
> Many thanks for the very detailed and highly informative pictures!!
> I appreciate your work. So thank you!

Glad to be of help!

> I am smiling to see you how you changed your mind from "garbage" to "a good toy" :)

Well, no, I didn't. I still consider it overpriced for what it is, and useless at the advertised purpose. Was it sold by an European dealer, they'd get it shipped return and I'd have my money back already. Being how it is, I'm trying to make use of what I got, was I to decide again, I'd go for some kit with a 18650 cell, this tiny battery here won't let esp32 run for long. This system works as a clock (I wouldn't call it a watch) for a measurable time only because the RTC wakes it for milliseconds once per minute. If you try fetching weather from the web for example, it won't be ready in milliseconds, you will need seconds of active mode (get WiFi up, connect, get response, process it and display) and battery life will plummet.

**Comment by robertio** [comment]
Hi.
This looks more matured, better priced, and have more hardware. (Battery management, buzzer, etc, )
Unfortunately it is not eink. 

https://www.banggood.com/LILYGO-TTGO-T-Watch-2020-ESP32-Main-Chip-1_54-Inch-Touch-Display-Programmable-Wearable-Environmental-Interaction-p-1671427.html

Thanks

**Comment by robertio** [comment]
[TTGO T-Watch-2020 ESP32](https://www.banggood.com/LILYGO-TTGO-T-Watch-2020-ESP32-Main-Chip-1_54-Inch-Touch-Display-Programmable-Wearable-Environmental-Interaction-p-1671427.html)

**Comment by Izaic** [comment]
> Hi.
> This (TTGO T-Watch-2020 ESP32) looks more matured, better priced, and have more hardware. (Battery management, buzzer, etc, )
> Unfortunately it is not eink.
> 
> https://www.banggood.com/LILYGO-TTGO-T-Watch-2020-ESP32-Main-Chip-1_54-Inch-Touch-Display-Programmable-Wearable-Environmental-Interaction-p-1671427.html
> 
> Thanks

I doo not recommend buying any lilygo watches either. I bought one and i was completely unable to open the device, which is how your supposed to be able to flash it. Look into the Pine64 pinetime, of which i can vouch for it's quality.
